"""
Typed state dictionary for the LangGraph investigation graph.

`SentinelState` is the single source of truth shared across all nodes in
the ARF Sentinel pipeline.  It is a TypedDict (from typing_extensions)
so that LangGraph can perform type‑safe state updates and validation.

Every field is documented below with its purpose and the node that
produces or consumes it.

Nodes that write to state:
    - discover_schema_node          → discovered_schema
    - investigate_dependencies_node → affected_repositories, dependency_paths,
                                       direct/transitive/affected counts
    - assess_blast_radius_node      → blast_radius_score, evidence_confidence,
                                       investigation_summary
    - propose_remediation_node      → proposed_action
    - arf_governance_node           → arf_event, arf_decision
    - prepare_execution_boundary_node → (no new fields)

Auxiliary fields:
    - reasoning_trace  : appended to by every node for audit/debug.
    - sql_queries      : populated when live CRAFT calls are made.
    - errors           : populated when any node encounters an exception.
"""

from typing import Any, Optional, List, Dict
from typing_extensions import TypedDict


class SentinelState(TypedDict, total=False):
    """
    Shared state for the ARF Sentinel LangGraph pipeline.

    Attributes
    ----------
    incident_id : str
        Unique identifier for the incident (generated at mission control).
    package_name : str
        The vulnerable package name (e.g., 'urllib3').
    vulnerability_description : str
        CVE or plain‑language description of the vulnerability.
    discovered_schema : dict
        Schema metadata discovered by CRAFT (tables, columns).
    affected_repositories : list of dict
        List of repositories affected, each with 'repo' and 'dependency' keys.
    dependency_paths : list of dict
        Directed edges from the vulnerable package to dependent repos.
    direct_dependency_count : int
        Number of direct dependencies (repos that import the package).
    transitive_dependency_count : int
        Number of transitive dependencies (indirectly exposed).
    affected_repository_count : int
        Total number of repositories in the blast radius.
    evidence_confidence : float
        Estimated reliability of the CRAFT data, C ∈ [0, 1].
    blast_radius_score : float
        Normalised impact score B ∈ [0, 1].
    investigation_summary : str
        Human‑readable summary of the CRAFT investigation.
    proposed_action : dict
        Serialised RemediationProposal (from Nemotron).
    arf_event : dict
        Serialised ARF ReliabilityEvent (if real ARF is used).
    arf_decision : dict
        Serialised GovernanceDecision (the binding result).
    execution_status : str
        Outcome of the execution boundary check.
    sql_queries : list of str
        SQL queries generated by CRAFT (populated in production).
    reasoning_trace : list of str
        Step‑by‑step trace of node execution (for audit/debug).
    errors : list of str
        Error messages collected during pipeline execution.
    """

    incident_id: str
    package_name: str
    vulnerability_description: str
    discovered_schema: Dict[str, Any]
    affected_repositories: List[Dict[str, Any]]
    dependency_paths: List[Dict[str, Any]]
    direct_dependency_count: int
    transitive_dependency_count: int
    affected_repository_count: int
    evidence_confidence: float
    blast_radius_score: float
    investigation_summary: str
    proposed_action: Dict[str, Any]
    arf_event: Dict[str, Any]
    arf_decision: Dict[str, Any]
    execution_status: str
    sql_queries: List[str]
    reasoning_trace: List[str]
    errors: List[str]
